let map = new Map(9,9)
let snake = new Snake(2,4,"right")
let apple = new Apple(3,4)
let apple2 = new Apple(7,6)
let rat1 = new Rat(8,2)
let rat2 = new Rat(1,3)
let rock1 = new Rock(8,3)
let rock2 = new Rock(1,6)

map.children.push(snake)
map.children.push(apple)
map.children.push(apple2)
map.children.push(rat1)
map.children.push(rat2)
map.children.push(rock1)
map.children.push(rock2)

map.render(container)